apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app
spec:
  template:
    spec:
      containers:
      - name: my-k8s-app
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi